### ISSUE TITLE
Upload lib to conan.io

### ISSUE THREAD

**Issue by agauniyal** [agauniyal/rang#29]
- https://www.conan.io/
 - https://github.com/conan-io/docs/issues/67

Make sure to open PR against [develop](https://github.com/agauniyal/rang/tree/develop) branch and not the master branch.

**Comment by zeokav** [comment]
Hi! I'm new to the conan package manager and I need some clarifications for this issue. I have made a conanfile.py, exported it, which on installing is installing from the local conan sources and writing a package to /home/[username]/.conan/data/rang/1.0/zeokav/test/package/[packagename]
This package has the rang.hpp file that's required.

But on including it in a cpp file and executing it, it can't find the header. What am I missing? I can't find a lot of information about conan. Thanks!

**Comment by agauniyal** [comment]
@zeokav tbh I haven't looked into conan docs yet(currently tight on schedule) but I've linked a past discussion above - https://github.com/conan-io/docs/issues/67. Here's one repo - https://github.com/memsharded/conan-date with single header solution, similar to us. 

You can always open an issue on https://github.com/conan-io/docs/issues for resolving your query or comment on existing issue that I've linked above.

I'm sorry I'm of no real help here since even I've no experience with conan either :confused:

**Comment by agauniyal** [comment]
Another thing is you might want to submit PR against develop branch and not the master branch because develop branch has the latest changes on it :smile:

**Comment by zeokav** [comment]
I went through that discussion and the conan-date example. Where exactly is the header supposed to be placed when the package is downloaded? That should solve the problem. I include it using double quotes and it works fine ONLY when the cpp and the rang.hpp are in the same directory! :/

I'll submit a PR to the development branch tomorrow if I can figure something out!

**Comment by agauniyal** [comment]
I've pinged conan's developer for some support. Unfortunately I'm unable to use conan since it's refusing to install on my system for unknown dep resolution bug - 
```
loading packages...
resolving dependencies...
warning: cannot resolve "python-patch=1.16", a dependency of "conan"
warning: cannot resolve "python-fasteners>=0.14.1", a dependency of "conan"
:: The following package cannot be upgraded due to unresolvable dependencies:
      conan

:: Do you want to skip the above package for this upgrade? [y/N] n
error: failed to prepare transaction (could not satisfy dependencies)
:: conan: requires python-patch=1.16
:: conan: requires python-fasteners>=0.14.1
==> WARNING: Your packages are saved in /tmp/yaourt-tmp-agauniyal
```
Anyways I'll build it manually and look into this issue this weekend if it's not solved by then. Till then the only advice I could provide you is go through the docs - http://docs.conan.io/en/latest/getting_started.html to see if there's something to help.

**Comment by memsharded** [comment]
Hi there!

Conan maintainer here, willing to help. 

About the installation of conan for ArchLinux, it seems that you didn't install those dependencies, please check: http://docs.conan.io/en/latest/installation.html#install-from-aur-arch-linux. and also the thread on: https://github.com/conan-io/conan/issues/21

Also @tivek is the maintainer of the package, you might ask him too for help.

**Comment by memsharded** [comment]
I have created a package for rang, for header only libraries is always very similar, so when you know a bit about the conan recipes and flows, it is not difficult (I did it in about 3 minutes):

- Github repo for the recipe: https://github.com/memsharded/conan-rang
- Package in conan.io: https://www.conan.io/source/rang/1.0/memsharded/stable

I have create a package recipe **outside** the repo. This is a simple approach for creating packages for releases. I have created a package for v1.0. It is also possible to create packages from within the library, mainly "snapshoting" the code into the package recipe, though it can also use ``source()`` to clone the repo and get any specific version, branch or tag. It is also possible to download the .zip.

I have used the following command:
```bash
$ conan new rang/1.0@memsharded/stable -t -i
```
It creates the skeleton for a header only library, quite simple to fill the voids. It also creates a ``test_package`` with a simple example, very useful to ensure that the package is properly created. I added the ``build_policy=missing`` so it is not necessary to have the package, it will be created by the recipe on demand.

Then, I tested the package with:
```bash
$ conan test_package
```
Worked fine in Win, VS14u2.

Finally, uploaded to conan:
```bash
$ conan upload rang/1.0@memsharded/stable -r=conan.io --all
```

We can create also a "develop" version package, that always point to the latest code in github, though this version is not good for reproducibility. For that purpose, the ``build_policy=always`` can be useful.

Now I will be offline for a few hours, but if you need more help, please ping me at info@conan.io, and we can chat too. Cheers!

**Comment by zeokav** [comment]
Thank you for your help, @memsharded. I'd done pretty much the same thing, except I didn't put the third argument in copy (rang/include). I'll push the code with these changes soon. :)

**Comment by memsharded** [comment]
Tip: Don't be afraid to get into the ``~/.conan/data`` folder and inspect what is there. It is very transparent. Going into the build/shaxxxx folder, you can clearly see the structure of folders and know better what is there, to put in the ``copy`` command. Similar for example into the ``export`` folder to check if you are doing an in-source package, or into the ``package/shaxxxx`` folder to verify that everything was copied fine.

Just tell me if you need something else :)

**Comment by agauniyal** [comment]
@memsharded Thankyou 😄 that was some quality support there. I managed to install conan via pip before seeing this message, however ran into same problem as mentioned by @zeokav and now it's resolved thanks to you.

@zeokav if everything's clear you can make a PR against latest develop branch instead of master :)

**Comment by memsharded** [comment]
You are welcome :) Indeed the preferred way to install conan is the python **pip** package. We have found is the more convenient and less troublesome. Cheers!
